modLoader="javafml"
loaderVersion="[42,)"
issueTrackerURL="https://gitlab.com/modding-legacy/ender-chested/issues"
license="https://moddinglegacy.com/ML-General-Terms/"
[[mods]]
modId="ender_chested"
version="${file.jarVersion}"
displayName="Ender Chested"
updateJSONURL="http://changelogs.moddinglegacy.com/ender-chest-horses.json"
displayURL="https://moddinglegacy.com/"
authors="KingPhygieBoo, Silver_David, Jonathing"
description='''
A simple mod that allows horses to be equipped with Ender Chests.'''
[[dependencies.ender_chested]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ender_chested]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
